project_id = "ekrwjfdypqzequovmvjn"

[functions.send-email]
verify_jwt = true

[functions.fetch-gmail-emails]
verify_jwt = true

[functions.gmail-integration]
verify_jwt = false

[functions.ringcentral-messages]
verify_jwt = true