-- Insert additional airport codes (batch 3)
INSERT INTO public.airport_codes (iata_code, name, city, country) VALUES
('HIB', 'Range Regional Airport', 'Hibbing', 'United States'),
('HLN', 'Helena Regional Airport', 'Helena', 'United States'),
('HOB', 'Lea County Regional Airport', 'Hobbs', 'United States'),
('HON', 'Huron Regional Airport', 'Huron', 'United States'),
('HOT', 'Memorial Field Airport', 'Hot Springs', 'United States'),
('HOU', 'William P. Hobby Airport', 'Houston', 'United States'),
('HPN', 'Westchester County Airport', 'White Plains', 'United States'),
('HRL', 'Valley International Airport', 'Harlingen', 'United States'),
('HSV', 'Huntsville International Airport', 'Huntsville', 'United States'),
('HTS', 'Tri-State Airport', 'Huntington', 'United States'),
('HUF', 'Terre Haute Regional Airport', 'Terre Haute', 'United States'),
('HUS', 'Hughes Airport', 'Hughes', 'United States'),
('HYA', 'Barnstable Municipal Airport', 'Hyannis', 'United States'),
('HYS', 'Hays Regional Airport', 'Hays', 'United States'),
('IAD', 'Washington Dulles International Airport', 'Dulles', 'United States'),
('IAG', 'Niagara Falls International Airport', 'Niagara Falls', 'United States'),
('IAH', 'George Bush Intercontinental Airport', 'Houston', 'United States'),
('ICT', 'Wichita Dwight D. Eisenhower National Airport', 'Wichita', 'United States'),
('IDA', 'Idaho Falls Regional Airport', 'Idaho Falls', 'United States'),
('IFP', 'Laughlin/Bullhead International Airport', 'Bullhead City', 'United States'),
('ILG', 'Wilmington Airport', 'Wilmington', 'United States'),
('ILM', 'Wilmington International Airport', 'Wilmington', 'United States'),
('IMT', 'Iron Mountain Airport', 'Iron Mountain', 'United States'),
('IND', 'Indianapolis International Airport', 'Indianapolis', 'United States'),
('INL', 'Falls International Airport', 'International Falls', 'United States'),
('IPL', 'Imperial County Airport', 'Imperial', 'United States'),
('ISP', 'Long Island MacArthur Airport', 'Islip', 'United States'),
('ITH', 'Ithaca Tompkins Regional Airport', 'Ithaca', 'United States'),
('ITO', 'Hilo International Airport', 'Hilo', 'United States'),
('JAC', 'Jackson Hole Airport', 'Jackson', 'United States'),
('JAN', 'Jackson–Medgar Wiley Evers International Airport', 'Jackson', 'United States'),
('JAX', 'Jacksonville International Airport', 'Jacksonville', 'United States'),
('JFK', 'John F. Kennedy International Airport', 'New York City', 'United States'),
('JLN', 'Joplin Regional Airport', 'Joplin', 'United States'),
('JMS', 'Jamestown Regional Airport', 'Jamestown', 'United States'),
('JNU', 'Juneau International Airport', 'Juneau', 'United States'),
('JST', 'Johnstown–Cambria County Airport', 'Johnstown', 'United States'),
('LAN', 'Capital Region International Airport', 'Lansing', 'United States'),
('LAR', 'Laramie Regional Airport', 'Laramie', 'United States'),
('LAS', 'Harry Reid International Airport', 'Las Vegas', 'United States'),
('LAW', 'Lawton–Fort Sill Regional Airport', 'Lawton', 'United States'),
('LAX', 'Los Angeles International Airport', 'Los Angeles', 'United States'),
('LBB', 'Lubbock Preston Smith International Airport', 'Lubbock', 'United States'),
('LBE', 'Arnold Palmer Regional Airport', 'Latrobe', 'United States'),
('LBL', 'Liberal Mid-America Regional Airport', 'Liberal', 'United States'),
('LCH', 'Lake Charles Regional Airport', 'Lake Charles', 'United States'),
('LEX', 'Blue Grass Airport', 'Lexington', 'United States'),
('LFT', 'Lafayette Regional Airport', 'Lafayette', 'United States'),
('LGA', 'LaGuardia Airport', 'New York City', 'United States'),
('LGB', 'Long Beach Airport', 'Long Beach', 'United States'),
('LIT', 'Bill and Hillary Clinton National Airport', 'Little Rock', 'United States'),
('LMT', 'Klamath Falls Airport', 'Klamath Falls', 'United States'),
('LNK', 'Lincoln Airport', 'Lincoln', 'United States'),
('LRD', 'Laredo International Airport', 'Laredo', 'United States'),
('LSE', 'La Crosse Regional Airport', 'La Crosse', 'United States'),
('LWS', 'Lewiston–Nez Perce County Airport', 'Lewiston', 'United States'),
('LYH', 'Lynchburg Regional Airport', 'Lynchburg', 'United States'),
('MAF', 'Midland International Air and Space Port', 'Midland', 'United States'),
('MBS', 'MBS International Airport', 'Freeland', 'United States'),
('MCI', 'Kansas City International Airport', 'Kansas City', 'United States'),
('MCK', 'McCook Ben Nelson Regional Airport', 'McCook', 'United States'),
('MCO', 'Orlando International Airport', 'Orlando', 'United States'),
('MDT', 'Harrisburg International Airport', 'Harrisburg', 'United States'),
('MDW', 'Midway International Airport', 'Chicago', 'United States'),
('MEI', 'Meridian Regional Airport', 'Meridian', 'United States'),
('MEM', 'Memphis International Airport', 'Memphis', 'United States'),
('MFE', 'McAllen Miller International Airport', 'McAllen', 'United States'),
('MFR', 'Rogue Valley International–Medford Airport', 'Medford', 'United States'),
('MGM', 'Montgomery Regional Airport', 'Montgomery', 'United States'),
('MHK', 'Manhattan Regional Airport', 'Manhattan', 'United States'),
('MHT', 'Manchester–Boston Regional Airport', 'Manchester', 'United States'),
('MIA', 'Miami International Airport', 'Miami', 'United States'),
('MKE', 'Milwaukee Mitchell International Airport', 'Milwaukee', 'United States'),
('MKG', 'Muskegon County Airport', 'Muskegon', 'United States'),
('MLB', 'Melbourne Orlando International Airport', 'Melbourne', 'United States'),
('MLI', 'Quad City International Airport', 'Moline', 'United States'),
('MLU', 'Monroe Regional Airport', 'Monroe', 'United States'),
('MMH', 'Mammoth Yosemite Airport', 'Mammoth Lakes', 'United States'),
('MOB', 'Mobile Regional Airport', 'Mobile', 'United States'),
('MOD', 'Modesto City–County Airport', 'Modesto', 'United States'),
('MOT', 'Minot International Airport', 'Minot', 'United States'),
('MQT', 'Marquette Sawyer Regional Airport', 'Marquette', 'United States'),
('MRY', 'Monterey Regional Airport', 'Monterey', 'United States'),
('MSN', 'Dane County Regional Airport', 'Madison', 'United States'),
('MSO', 'Missoula International Airport', 'Missoula', 'United States'),
('MSP', 'Minneapolis–Saint Paul International Airport', 'Minneapolis', 'United States'),
('MSY', 'Louis Armstrong New Orleans International Airport', 'New Orleans', 'United States'),
('MTJ', 'Montrose Regional Airport', 'Montrose', 'United States'),
('MVY', 'Martha''s Vineyard Airport', 'Vineyard Haven', 'United States'),
('MYR', 'Myrtle Beach International Airport', 'Myrtle Beach', 'United States')
ON CONFLICT (iata_code) DO UPDATE SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  country = EXCLUDED.country;