-- Insert major international airport codes
INSERT INTO public.airport_codes (iata_code, name, city, country) VALUES
('AMS', 'Amsterdam Airport Schiphol', 'Amsterdam', 'Netherlands'),
('ARN', 'Stockholm Arlanda Airport', 'Stockholm', 'Sweden'),
('ATH', 'Eleftherios Venizelos Airport', 'Athens', 'Greece'),
('AUH', 'Abu Dhabi International Airport', 'Abu Dhabi', 'United Arab Emirates'),
('BCN', 'Barcelona El Prat Airport', 'Barcelona', 'Spain'),
('BKK', 'Suvarnabhumi Airport', 'Bangkok', 'Thailand'),
('BOG', 'El Dorado International Airport', 'Bogotá', 'Colombia'),
('BRU', 'Brussels Airport', 'Brussels', 'Belgium'),
('BUD', 'Budapest Ferenc Liszt International Airport', 'Budapest', 'Hungary'),
('CAI', 'Cairo International Airport', 'Cairo', 'Egypt'),
('CAN', 'Guangzhou Baiyun International Airport', 'Guangzhou', 'China'),
('CDG', 'Charles de Gaulle Airport', 'Paris', 'France'),
('CGK', 'Soekarno–Hatta International Airport', 'Jakarta', 'Indonesia'),
('CPT', 'Cape Town International Airport', 'Cape Town', 'South Africa'),
('DEL', 'Indira Gandhi International Airport', 'Delhi', 'India'),
('DME', 'Domodedovo International Airport', 'Moscow', 'Russia'),
('DOH', 'Hamad International Airport', 'Doha', 'Qatar'),
('DUB', 'Dublin Airport', 'Dublin', 'Ireland'),
('DXB', 'Dubai International Airport', 'Dubai', 'United Arab Emirates'),
('EDI', 'Edinburgh Airport', 'Edinburgh', 'United Kingdom'),
('FCO', 'Leonardo da Vinci–Fiumicino Airport', 'Rome', 'Italy'),
('FRA', 'Frankfurt Airport', 'Frankfurt', 'Germany'),
('GRU', 'Guarulhos International Airport', 'São Paulo', 'Brazil'),
('GVA', 'Geneva Airport', 'Geneva', 'Switzerland'),
('HKG', 'Hong Kong International Airport', 'Hong Kong', 'Hong Kong'),
('ICN', 'Incheon International Airport', 'Seoul', 'South Korea'),
('IST', 'Istanbul Airport', 'Istanbul', 'Turkey'),
('KIX', 'Kansai International Airport', 'Osaka', 'Japan'),
('KUL', 'Kuala Lumpur International Airport', 'Kuala Lumpur', 'Malaysia'),
('LHR', 'London Heathrow Airport', 'London', 'United Kingdom'),
('LGW', 'London Gatwick Airport', 'London', 'United Kingdom'),
('LIM', 'Jorge Chávez International Airport', 'Lima', 'Peru'),
('LIS', 'Humberto Delgado Airport', 'Lisbon', 'Portugal'),
('MAD', 'Adolfo Suárez Madrid–Barajas Airport', 'Madrid', 'Spain'),
('MAN', 'Manchester Airport', 'Manchester', 'United Kingdom'),
('MEX', 'Mexico City International Airport', 'Mexico City', 'Mexico'),
('MUC', 'Munich Airport', 'Munich', 'Germany'),
('NRT', 'Narita International Airport', 'Tokyo', 'Japan'),
('OSL', 'Oslo Gardermoen Airport', 'Oslo', 'Norway'),
('OTP', 'Henri Coandă International Airport', 'Bucharest', 'Romania'),
('PEK', 'Beijing Capital International Airport', 'Beijing', 'China'),
('PRG', 'Václav Havel Airport Prague', 'Prague', 'Czech Republic'),
('RUH', 'King Khalid International Airport', 'Riyadh', 'Saudi Arabia'),
('SCL', 'Comodoro Arturo Merino Benítez International Airport', 'Santiago', 'Chile'),
('SGN', 'Tan Son Nhat International Airport', 'Ho Chi Minh City', 'Vietnam'),
('SIN', 'Singapore Changi Airport', 'Singapore', 'Singapore'),
('SVO', 'Sheremetyevo International Airport', 'Moscow', 'Russia'),
('SYD', 'Sydney Kingsford Smith Airport', 'Sydney', 'Australia'),
('TPE', 'Taoyuan International Airport', 'Taipei', 'Taiwan'),
('VIE', 'Vienna International Airport', 'Vienna', 'Austria'),
('WAW', 'Warsaw Chopin Airport', 'Warsaw', 'Poland'),
('YVR', 'Vancouver International Airport', 'Vancouver', 'Canada'),
('YYC', 'Calgary International Airport', 'Calgary', 'Canada'),
('YYZ', 'Toronto Pearson International Airport', 'Toronto', 'Canada'),
('ZRH', 'Zurich Airport', 'Zurich', 'Switzerland')
ON CONFLICT (iata_code) DO UPDATE SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  country = EXCLUDED.country;