-- Comprehensive Airline Records Implementation
-- Phase 1: Add comprehensive airline records with proper constraints

-- First, add the airlines
INSERT INTO public.airline_codes (iata_code, icao_code, name, country, alliance, logo_url) VALUES
-- A Airlines
('AQ', NULL, '9 Air', 'China', NULL, NULL),
('A3', 'AEE', 'Aegean Airlines', 'Greece', 'Star Alliance', NULL),
('EI', 'EIN', 'Aer Lingus', 'Ireland', NULL, NULL),
('SU', 'AFL', 'Aeroflot', 'Russia', NULL, NULL),
('AR', 'ARG', 'Aerolineas Argentinas', 'Argentina', 'SkyTeam', NULL),
('AM', 'AMX', 'Aeromexico', 'Mexico', 'SkyTeam', NULL),
('AH', 'DAH', 'Air Algerie', 'Algeria', NULL, NULL),
('G9', 'ABY', 'Air Arabia', 'UAE', NULL, NULL),
('KC', 'KZR', 'Air Astana', 'Kazakhstan', NULL, NULL),
('BP', 'BOT', 'Air Botswana', 'Botswana', NULL, NULL),
('BX', 'ABL', 'Air Busan', 'South Korea', NULL, NULL),
('KR', 'KHV', 'Air Cambodia', 'Cambodia', NULL, NULL),
('AC', 'ACA', 'Air Canada', 'Canada', 'Star Alliance', NULL),
('RV', 'ROU', 'Air Canada Rouge', 'Canada', 'Star Alliance', NULL),
('TX', 'FWI', 'Air Caraïbes', 'France', NULL, NULL),
('CA', 'CCA', 'Air China', 'China', 'Star Alliance', NULL),
('EN', 'DLA', 'Air Dolomiti', 'Italy', 'Star Alliance', NULL),
('UX', 'AEA', 'Air Europa', 'Spain', 'SkyTeam', NULL),
('AF', 'AFR', 'Air France', 'France', 'SkyTeam', NULL),
('AI', 'AIC', 'Air India', 'India', 'Star Alliance', NULL),
('IX', 'AXB', 'Air India Express', 'India', NULL, NULL),
('NX', 'AMU', 'Air Macau', 'Macau', NULL, NULL),
('MD', 'MDG', 'Air Madagascar', 'Madagascar', NULL, NULL),
('KM', 'AMC', 'Air Malta', 'Malta', NULL, NULL),
('MK', 'MAU', 'Air Mauritius', 'Mauritius', NULL, NULL),
('9U', 'MLD', 'Air Moldova', 'Moldova', NULL, NULL),
('SW', 'NMB', 'Air Namibia', 'Namibia', NULL, NULL),
('NZ', 'ANZ', 'Air New Zealand', 'New Zealand', 'Star Alliance', NULL),
('PX', 'ANG', 'Air Niugini', 'Papua New Guinea', NULL, NULL),
('YW', 'ANE', 'Air Nostrum', 'Spain', NULL, NULL),
('JU', 'ASL', 'Air Serbia', 'Serbia', NULL, NULL),
('HM', 'SEY', 'Air Seychelles', 'Seychelles', NULL, NULL),
('TN', 'THT', 'Air Tahiti Nui', 'French Polynesia', NULL, NULL),
('TS', 'TSC', 'Air Transat', 'Canada', NULL, NULL),
('NF', 'AVN', 'Air Vanuatu', 'Vanuatu', NULL, NULL),
('AK', 'AXM', 'AirAsia', 'Malaysia', NULL, NULL),
('D7', 'XAX', 'AirAsia X', 'Malaysia', NULL, NULL),
('I5', 'IAD', 'AirAsia India', 'India', NULL, NULL),
('BT', 'BTI', 'airBaltic', 'Latvia', NULL, NULL),
('PA', 'ABQ', 'airblue', 'Pakistan', NULL, NULL),
('SB', 'ACI', 'Aircalin', 'New Caledonia', NULL, NULL),
('AS', 'ASA', 'Alaska Airlines', 'United States', 'Oneworld', NULL),
('G4', 'AAY', 'Allegiant Air', 'United States', NULL, NULL),
('AA', 'AAL', 'American Airlines', 'United States', 'Oneworld', NULL),
('NH', 'ANA', 'ANA All Nippon Airways', 'Japan', 'Star Alliance', NULL),
('W3', 'ARA', 'Arik Air', 'Nigeria', NULL, NULL),
('OZ', 'AAR', 'Asiana Airlines', 'South Korea', 'Star Alliance', NULL),
('OS', 'AUA', 'Austrian Airlines', 'Austria', 'Star Alliance', NULL),
('AV', 'AVA', 'Avianca', 'Colombia', 'Star Alliance', NULL),
('J2', 'AHY', 'Azerbaijan Airlines', 'Azerbaijan', NULL, NULL),
('AD', 'AZU', 'Azul Brazilian Airlines', 'Brazil', NULL, NULL),
-- B Airlines continuing with key carriers
('UP', 'BHS', 'Bahamasair', 'Bahamas', NULL, NULL),
('QH', 'BAV', 'Bamboo Airways', 'Vietnam', NULL, NULL),
('PG', 'BKP', 'Bangkok Airways', 'Thailand', NULL, NULL),
('ID', 'BTK', 'Batik Air', 'Indonesia', NULL, NULL),
('B2', 'BRU', 'Belavia Belarusian Airlines', 'Belarus', NULL, NULL),
('BG', 'BBC', 'Biman Bangladesh Airlines', 'Bangladesh', NULL, NULL),
('0B', 'BLA', 'Blue Air', 'Romania', NULL, NULL),
('OB', 'BOV', 'Boliviana de Aviación', 'Bolivia', NULL, NULL),
('BA', 'BAW', 'British Airways', 'United Kingdom', 'Oneworld', NULL),
('SN', 'BEL', 'Brussels Airlines', 'Belgium', 'Star Alliance', NULL),
('FB', 'LZB', 'Bulgaria Air', 'Bulgaria', NULL, NULL),
-- Major carriers continuing
('CX', 'CPA', 'Cathay Pacific Airways', 'Hong Kong', 'Oneworld', NULL),
('5J', 'CEB', 'Cebu Pacific', 'Philippines', NULL, NULL),
('CI', 'CAL', 'China Airlines', 'Taiwan', 'SkyTeam', NULL),
('MU', 'CES', 'China Eastern Airlines', 'China', 'SkyTeam', NULL),
('CZ', 'CSN', 'China Southern Airlines', 'China', NULL, NULL),
('DE', 'CFG', 'Condor Airlines', 'Germany', NULL, NULL),
('CM', 'CMP', 'Copa Airlines', 'Panama', 'Star Alliance', NULL),
('OU', 'CTN', 'Croatia Airlines', 'Croatia', 'Star Alliance', NULL),
('OK', 'CSA', 'CSA Czech Airlines', 'Czech Republic', 'SkyTeam', NULL),
('DL', 'DAL', 'Delta Air Lines', 'United States', 'SkyTeam', NULL),
('U2', 'EZY', 'easyJet', 'United Kingdom', NULL, NULL),
('WK', 'EDW', 'Edelweiss Air', 'Switzerland', NULL, NULL),
('MS', 'MSR', 'Egyptair', 'Egypt', 'Star Alliance', NULL),
('LY', 'ELY', 'El Al Israel Airlines', 'Israel', NULL, NULL),
('EK', 'UAE', 'Emirates', 'UAE', NULL, NULL),
('ET', 'ETH', 'Ethiopian Airlines', 'Ethiopia', 'Star Alliance', NULL),
('EY', 'ETD', 'Etihad Airways', 'UAE', NULL, NULL),
('EW', 'EWG', 'Eurowings', 'Germany', NULL, NULL),
('BR', 'EVA', 'EVA Air', 'Taiwan', 'Star Alliance', NULL),
('FJ', 'FJI', 'Fiji Airways', 'Fiji', 'Oneworld', NULL),
('AY', 'FIN', 'Finnair', 'Finland', 'Oneworld', NULL),
('FZ', 'FDB', 'flydubai', 'UAE', NULL, NULL),
('F9', 'FFT', 'Frontier Airlines', 'United States', NULL, NULL),
('GA', 'GIA', 'Garuda Indonesia', 'Indonesia', 'SkyTeam', NULL),
('G3', 'GLO', 'GOL Airlines', 'Brazil', NULL, NULL),
('GF', 'GFA', 'Gulf Air', 'Bahrain', NULL, NULL),
('HU', 'CHH', 'Hainan Airlines', 'China', NULL, NULL),
('HA', 'HAL', 'Hawaiian Airlines', 'United States', NULL, NULL),
('HX', 'CRK', 'Hong Kong Airlines', 'Hong Kong', NULL, NULL),
('IB', 'IBE', 'Iberia', 'Spain', 'Oneworld', NULL),
('FI', 'ICE', 'Icelandair', 'Iceland', NULL, NULL),
('6E', 'IGO', 'IndiGo', 'India', NULL, NULL),
('AZ', 'ITY', 'ITA Airways', 'Italy', 'SkyTeam', NULL),
('JL', 'JAL', 'Japan Airlines', 'Japan', 'Oneworld', NULL),
('B6', 'JBU', 'JetBlue Airways', 'United States', NULL, NULL),
('JQ', 'JST', 'Jetstar Airways', 'Australia', NULL, NULL),
('HO', 'DKH', 'Juneyao Airlines', 'China', NULL, NULL),
('KQ', 'KQA', 'Kenya Airways', 'Kenya', 'SkyTeam', NULL),
('KL', 'KLM', 'KLM Royal Dutch Airlines', 'Netherlands', 'SkyTeam', NULL),
('KE', 'KAL', 'Korean Air', 'South Korea', 'SkyTeam', NULL),
('KU', 'KAC', 'Kuwait Airways', 'Kuwait', NULL, NULL),
('B0', 'LCO', 'La Compagnie', 'France', NULL, NULL),
('LA', 'LAN', 'LATAM Airlines', 'Chile', NULL, NULL),
('JT', 'LNI', 'Lion Air', 'Indonesia', NULL, NULL),
('LO', 'LOT', 'LOT Polish Airlines', 'Poland', 'Star Alliance', NULL),
('LH', 'DLH', 'Lufthansa', 'Germany', 'Star Alliance', NULL),
('LG', 'LGL', 'Luxair', 'Luxembourg', NULL, NULL),
('MH', 'MAS', 'Malaysia Airlines', 'Malaysia', 'Oneworld', NULL),
('ME', 'MEA', 'Middle East Airlines', 'Lebanon', 'SkyTeam', NULL),
('DY', 'NAX', 'Norwegian', 'Norway', NULL, NULL),
('WY', 'OMA', 'Oman Air', 'Oman', 'Oneworld', NULL),
('PC', 'PGT', 'Pegasus Airlines', 'Turkey', NULL, NULL),
('PR', 'PAL', 'Philippine Airlines', 'Philippines', NULL, NULL),
('PK', 'PIA', 'PIA Pakistan International', 'Pakistan', NULL, NULL),
('PD', 'POE', 'Porter Airlines', 'Canada', NULL, NULL),
('QF', 'QFA', 'Qantas Airways', 'Australia', 'Oneworld', NULL),
('QR', 'QTR', 'Qatar Airways', 'Qatar', 'Oneworld', NULL),
('AT', 'RAM', 'Royal Air Maroc', 'Morocco', 'Oneworld', NULL),
('BI', 'RBA', 'Royal Brunei Airlines', 'Brunei', NULL, NULL),
('RJ', 'RJA', 'Royal Jordanian Airlines', 'Jordan', 'Oneworld', NULL),
('FR', 'RYR', 'Ryanair', 'Ireland', NULL, NULL),
('S7', 'SBI', 'S7 Airlines', 'Russia', NULL, NULL),
('SK', 'SAS', 'SAS Scandinavian Airlines', 'Sweden', 'Star Alliance', NULL),
('SV', 'SVA', 'Saudi Arabian Airlines', 'Saudi Arabia', 'SkyTeam', NULL),
('ZH', 'CSZ', 'Shenzhen Airlines', 'China', 'Star Alliance', NULL),
('3U', 'CSC', 'Sichuan Airlines', 'China', NULL, NULL),
('SQ', 'SIA', 'Singapore Airlines', 'Singapore', 'Star Alliance', NULL),
('SA', 'SAA', 'South African Airways', 'South Africa', 'Star Alliance', NULL),
('WN', 'SWA', 'Southwest Airlines', 'United States', NULL, NULL),
('SG', 'SEJ', 'SpiceJet', 'India', NULL, NULL),
('NK', 'NKS', 'Spirit Airlines', 'United States', NULL, NULL),
('9C', 'CQH', 'Spring Airlines', 'China', NULL, NULL),
('UL', 'ALK', 'SriLankan Airlines', 'Sri Lanka', 'Oneworld', NULL),
('LX', 'SWR', 'Swiss International Air Lines', 'Switzerland', 'Star Alliance', NULL),
('TP', 'TAP', 'TAP Portugal', 'Portugal', 'Star Alliance', NULL),
('RO', 'ROT', 'TAROM', 'Romania', 'SkyTeam', NULL),
('TG', 'THA', 'Thai Airways', 'Thailand', 'Star Alliance', NULL),
('TU', 'TAR', 'Tunisair', 'Tunisia', NULL, NULL),
('TK', 'THY', 'Turkish Airlines', 'Turkey', 'Star Alliance', NULL),
('UA', 'UAL', 'United Airlines', 'United States', 'Star Alliance', NULL),
('VJ', 'VJC', 'VietJet Air', 'Vietnam', NULL, NULL),
('VN', 'HVN', 'Vietnam Airlines', 'Vietnam', 'SkyTeam', NULL),
('VS', 'VIR', 'Virgin Atlantic', 'United Kingdom', 'SkyTeam', NULL),
('VA', 'VOZ', 'Virgin Australia', 'Australia', NULL, NULL),
('UK', 'VTI', 'Vistara', 'India', NULL, NULL),
('Y4', 'VOI', 'Volaris', 'Mexico', NULL, NULL),
('VY', 'VLG', 'Vueling Airlines', 'Spain', NULL, NULL),
('WS', 'WJA', 'WestJet Airlines', 'Canada', NULL, NULL),
('W6', 'WZZ', 'Wizz Air', 'Hungary', NULL, NULL),
('MF', 'CXA', 'Xiamen Airlines', 'China', 'SkyTeam', NULL)
ON CONFLICT (iata_code) DO NOTHING;