-- Insert US airports data
INSERT INTO public.airport_codes (iata_code, name, city, country) VALUES
('ABE', 'Lehigh Valley International Airport', 'Allentown', 'United States'),
('ABI', 'Abilene Regional Airport', 'Abilene', 'United States'),
('ABQ', 'Albuquerque International Sunport', 'Albuquerque', 'United States'),
('ABR', 'Aberdeen Regional Airport', 'Aberdeen', 'United States'),
('ABY', 'Southwest Georgia Regional Airport', 'Albany', 'United States'),
('ACK', 'Nantucket Memorial Airport', 'Nantucket', 'United States'),
('ACT', 'Waco Regional Airport', 'Waco', 'United States'),
('ACV', 'Arcata–Eureka Airport', 'Arcata/Eureka', 'United States'),
('ACY', 'Atlantic City International Airport', 'Atlantic City', 'United States'),
('ADM', 'Ardmore Municipal Airport', 'Ardmore', 'United States'),
('ADQ', 'Kodiak Airport', 'Kodiak', 'United States'),
('AEX', 'Alexandria International Airport', 'Alexandria', 'United States'),
('AGS', 'Augusta Regional Airport', 'Augusta', 'United States'),
('AKN', 'King Salmon Airport', 'King Salmon', 'United States'),
('ALB', 'Albany International Airport', 'Albany', 'United States'),
('ALO', 'Waterloo Regional Airport', 'Waterloo', 'United States'),
('ALS', 'San Luis Valley Regional Airport', 'Alamosa', 'United States'),
('ALW', 'Walla Walla Regional Airport', 'Walla Walla', 'United States'),
('AMA', 'Rick Husband Amarillo International Airport', 'Amarillo', 'United States'),
('ANC', 'Ted Stevens Anchorage International Airport', 'Anchorage', 'United States'),
('APN', 'Alpena County Regional Airport', 'Alpena', 'United States'),
('ASE', 'Aspen/Pitkin County Airport', 'Aspen', 'United States'),
('ATL', 'Hartsfield–Jackson Atlanta International Airport', 'Atlanta', 'United States'),
('ATW', 'Appleton International Airport', 'Appleton', 'United States'),
('ATY', 'Watertown Regional Airport', 'Watertown', 'United States'),
('AUG', 'Augusta State Airport', 'Augusta', 'United States'),
('AUS', 'Austin–Bergstrom International Airport', 'Austin', 'United States'),
('AVL', 'Asheville Regional Airport', 'Asheville', 'United States'),
('AVP', 'Wilkes-Barre/Scranton International Airport', 'Avoca', 'United States'),
('AZO', 'Kalamazoo/Battle Creek International Airport', 'Kalamazoo', 'United States'),
('BDL', 'Bradley International Airport', 'Windsor Locks', 'United States'),
('BET', 'Bethel Airport', 'Bethel', 'United States'),
('BFD', 'Bradford Regional Airport', 'Bradford', 'United States'),
('BFF', 'Western Nebraska Regional Airport', 'Scottsbluff', 'United States'),
('BFI', 'Boeing Field', 'Seattle', 'United States'),
('BFL', 'Meadows Field Airport', 'Bakersfield', 'United States'),
('BGM', 'Greater Binghamton Airport', 'Binghamton', 'United States'),
('BGR', 'Bangor International Airport', 'Bangor', 'United States'),
('BHM', 'Birmingham–Shuttlesworth International Airport', 'Birmingham', 'United States'),
('BIL', 'Billings Logan International Airport', 'Billings', 'United States'),
('BIS', 'Bismarck Municipal Airport', 'Bismarck', 'United States'),
('BJI', 'Bemidji Regional Airport', 'Bemidji', 'United States'),
('BLI', 'Bellingham International Airport', 'Bellingham', 'United States'),
('BMI', 'Central Illinois Regional Airport', 'Bloomington', 'United States'),
('BNA', 'Nashville International Airport', 'Nashville', 'United States'),
('BOI', 'Boise Airport', 'Boise', 'United States'),
('BOS', 'Logan International Airport', 'Boston', 'United States'),
('BPT', 'Southeast Texas Regional Airport', 'Beaumont/Port Arthur', 'United States'),
('BQK', 'Brunswick Golden Isles Airport', 'Brunswick', 'United States'),
('BQN', 'Rafael Hernández Airport', 'Aguadilla', 'Puerto Rico'),
('BRD', 'Brainerd Lakes Regional Airport', 'Brainerd', 'United States'),
('BRO', 'Brownsville/South Padre Island International Airport', 'Brownsville', 'United States'),
('BRW', 'Wiley Post–Will Rogers Memorial Airport', 'Barrow', 'United States'),
('BTM', 'Bert Mooney Airport', 'Butte', 'United States'),
('BTR', 'Baton Rouge Metropolitan Airport', 'Baton Rouge', 'United States'),
('BTV', 'Burlington International Airport', 'Burlington', 'United States'),
('BUF', 'Buffalo Niagara International Airport', 'Buffalo', 'United States'),
('BUR', 'Bob Hope Airport', 'Burbank', 'United States'),
('BWI', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore', 'United States'),
('BZN', 'Bozeman Yellowstone International Airport', 'Bozeman', 'United States'),
('CAE', 'Columbia Metropolitan Airport', 'Columbia', 'United States'),
('CAK', 'Akron–Canton Airport', 'Akron', 'United States'),
('CDC', 'Cedar City Regional Airport', 'Cedar City', 'United States'),
('CDV', 'Merle K. (Mudhole) Smith Airport', 'Cordova', 'United States'),
('CHA', 'Chattanooga Metropolitan Airport', 'Chattanooga', 'United States'),
('CHO', 'Charlottesville–Albemarle Airport', 'Charlottesville', 'United States'),
('CHS', 'Charleston International Airport', 'Charleston', 'United States'),
('CIC', 'Chico Municipal Airport', 'Chico', 'United States'),
('CID', 'Eastern Iowa Airport', 'Cedar Rapids', 'United States'),
('CIU', 'Chippewa County International Airport', 'Sault Ste. Marie', 'United States'),
('CLD', 'McClellan–Palomar Airport', 'Carlsbad', 'United States'),
('CLE', 'Cleveland Hopkins International Airport', 'Cleveland', 'United States'),
('CLL', 'Easterwood Airport', 'College Station', 'United States'),
('CLT', 'Charlotte Douglas International Airport', 'Charlotte', 'United States'),
('CMH', 'John Glenn Columbus International Airport', 'Columbus', 'United States'),
('CMI', 'University of Illinois Willard Airport', 'Champaign', 'United States'),
('CMX', 'Houghton County Memorial Airport', 'Hancock', 'United States'),
('COD', 'Yellowstone Regional Airport', 'Cody', 'United States'),
('COS', 'Colorado Springs Airport', 'Colorado Springs', 'United States'),
('COU', 'Columbia Regional Airport', 'Columbia', 'United States'),
('CPR', 'Casper–Natrona County International Airport', 'Casper', 'United States'),
('CRP', 'Corpus Christi International Airport', 'Corpus Christi', 'United States'),
('CRW', 'Yeager Airport', 'Charleston', 'United States'),
('CSG', 'Columbus Airport', 'Columbus', 'United States'),
('CVG', 'Cincinnati/Northern Kentucky International Airport', 'Covington', 'United States'),
('CWA', 'Central Wisconsin Airport', 'Mosinee', 'United States'),
('DAB', 'Daytona Beach International Airport', 'Daytona Beach', 'United States'),
('DAL', 'Dallas Love Field', 'Dallas', 'United States'),
('DAY', 'Dayton International Airport', 'Dayton', 'United States'),
('DBQ', 'Dubuque Regional Airport', 'Dubuque', 'United States'),
('DCA', 'Ronald Reagan Washington National Airport', 'Washington', 'United States'),
('DEN', 'Denver International Airport', 'Denver', 'United States'),
('DFW', 'Dallas/Fort Worth International Airport', 'Dallas/Fort Worth', 'United States'),
('DHN', 'Dothan Regional Airport', 'Dothan', 'United States'),
('DIK', 'Dickinson Theodore Roosevelt Regional Airport', 'Dickinson', 'United States'),
('DLH', 'Duluth International Airport', 'Duluth', 'United States'),
('DRO', 'Durango–La Plata County Airport', 'Durango', 'United States'),
('DRT', 'Del Rio International Airport', 'Del Rio', 'United States'),
('DSM', 'Des Moines International Airport', 'Des Moines', 'United States'),
('DTW', 'Detroit Metropolitan Wayne County Airport', 'Detroit', 'United States'),
('DVL', 'Devils Lake Regional Airport', 'Devils Lake', 'United States'),
('EAA', 'Eagle Airport', 'Eagle', 'United States'),
('EAT', 'Pangborn Memorial Airport', 'Wenatchee', 'United States'),
('EAU', 'Chippewa Valley Regional Airport', 'Eau Claire', 'United States'),
('ECP', 'Northwest Florida Beaches International Airport', 'Panama City', 'United States'),
('EGE', 'Eagle County Regional Airport', 'Eagle', 'United States'),
('EKO', 'Elko Regional Airport', 'Elko', 'United States'),
('ELM', 'Elmira/Corning Regional Airport', 'Elmira', 'United States'),
('ELP', 'El Paso International Airport', 'El Paso', 'United States'),
('ERI', 'Erie International Airport', 'Erie', 'United States'),
('ESC', 'Delta County Airport', 'Escanaba', 'United States'),
('EUG', 'Eugene Airport', 'Eugene', 'United States'),
('EVV', 'Evansville Regional Airport', 'Evansville', 'United States'),
('EWN', 'Coastal Carolina Regional Airport', 'New Bern', 'United States'),
('EWR', 'Newark Liberty International Airport', 'Newark', 'United States'),
('EYW', 'Key West International Airport', 'Key West', 'United States'),
('FAI', 'Fairbanks International Airport', 'Fairbanks', 'United States'),
('FAR', 'Hector International Airport', 'Fargo', 'United States'),
('FAT', 'Fresno Yosemite International Airport', 'Fresno', 'United States'),
('FAY', 'Fayetteville Regional Airport', 'Fayetteville', 'United States'),
('FLG', 'Flagstaff Pulliam Airport', 'Flagstaff', 'United States'),
('FLL', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale', 'United States'),
('FLO', 'Florence Regional Airport', 'Florence', 'United States'),
('FMN', 'Four Corners Regional Airport', 'Farmington', 'United States'),
('FNT', 'Flint Bishop International Airport', 'Flint', 'United States'),
('FOD', 'Fort Dodge Regional Airport', 'Fort Dodge', 'United States'),
('FOE', 'Topeka Regional Airport', 'Topeka', 'United States'),
('FSD', 'Sioux Falls Regional Airport', 'Sioux Falls', 'United States'),
('FSM', 'Fort Smith Regional Airport', 'Fort Smith', 'United States'),
('FWA', 'Fort Wayne International Airport', 'Fort Wayne', 'United States'),
('GCC', 'Gillette–Campbell County Airport', 'Gillette', 'United States'),
('GCK', 'Garden City Regional Airport', 'Garden City', 'United States'),
('GEG', 'Spokane International Airport', 'Spokane', 'United States'),
('GFK', 'Grand Forks International Airport', 'Grand Forks', 'United States'),
('GGG', 'East Texas Regional Airport', 'Longview', 'United States'),
('GGW', 'Glasgow International Airport', 'Glasgow', 'United States'),
('GJT', 'Grand Junction Regional Airport', 'Grand Junction', 'United States'),
('GLD', 'Renner Field', 'Goodland', 'United States'),
('GRB', 'Green Bay–Austin Straubel International Airport', 'Green Bay', 'United States'),
('GRI', 'Central Nebraska Regional Airport', 'Grand Island', 'United States'),
('GRK', 'Killeen–Fort Hood Regional Airport', 'Killeen', 'United States'),
('GRR', 'Gerald R. Ford International Airport', 'Grand Rapids', 'United States'),
('GSO', 'Piedmont Triad International Airport', 'Greensboro', 'United States'),
('GSP', 'Greenville–Spartanburg International Airport', 'Greer', 'United States'),
('GTB', 'Wheeler-Sack Army Airfield', 'Fort Drum', 'United States'),
('GTF', 'Great Falls International Airport', 'Great Falls', 'United States'),
('GTR', 'Golden Triangle Regional Airport', 'Columbus', 'United States'),
('GUC', 'Gunnison–Crested Butte Regional Airport', 'Gunnison', 'United States'),
('GUP', 'Gallup Municipal Airport', 'Gallup', 'United States'),
('GVT', 'Majors Airport', 'Greenville', 'United States'),
('GYY', 'Gary/Chicago International Airport', 'Gary', 'United States'),
('HDN', 'Yampa Valley Airport', 'Hayden', 'United States'),
('HIB', 'Range Regional Airport', 'Hibbing', 'United States'),
('HLN', 'Helena Regional Airport', 'Helena', 'United States'),
('HOB', 'Lea County Regional Airport', 'Hobbs', 'United States'),
('HON', 'Huron Regional Airport', 'Huron', 'United States'),
('HOT', 'Memorial Field Airport', 'Hot Springs', 'United States'),
('HOU', 'William P. Hobby Airport', 'Houston', 'United States'),
('HPN', 'Westchester County Airport', 'White Plains', 'United States'),
('HRL', 'Valley International Airport', 'Harlingen', 'United States'),
('HSV', 'Huntsville International Airport', 'Huntsville', 'United States'),
('HTS', 'Tri-State Airport', 'Huntington', 'United States'),
('HUF', 'Terre Haute Regional Airport', 'Terre Haute', 'United States'),
('HUS', 'Hughes Airport', 'Hughes', 'United States'),
('HYA', 'Barnstable Municipal Airport', 'Hyannis', 'United States'),
('HYS', 'Hays Regional Airport', 'Hays', 'United States'),
('IAD', 'Washington Dulles International Airport', 'Dulles', 'United States'),
('IAG', 'Niagara Falls International Airport', 'Niagara Falls', 'United States'),
('IAH', 'George Bush Intercontinental Airport', 'Houston', 'United States'),
('ICT', 'Wichita Dwight D. Eisenhower National Airport', 'Wichita', 'United States'),
('IDA', 'Idaho Falls Regional Airport', 'Idaho Falls', 'United States'),
('IFP', 'Laughlin/Bullhead International Airport', 'Bullhead City', 'United States'),
('ILG', 'Wilmington Airport', 'Wilmington', 'United States'),
('ILM', 'Wilmington International Airport', 'Wilmington', 'United States'),
('IMT', 'Iron Mountain Airport', 'Iron Mountain', 'United States'),
('IND', 'Indianapolis International Airport', 'Indianapolis', 'United States'),
('INL', 'Falls International Airport', 'International Falls', 'United States'),
('IPL', 'Imperial County Airport', 'Imperial', 'United States'),
('ISP', 'Long Island MacArthur Airport', 'Islip', 'United States'),
('ITH', 'Ithaca Tompkins Regional Airport', 'Ithaca', 'United States'),
('ITO', 'Hilo International Airport', 'Hilo', 'United States'),
('JAC', 'Jackson Hole Airport', 'Jackson', 'United States'),
('JAN', 'Jackson–Medgar Wiley Evers International Airport', 'Jackson', 'United States'),
('JAX', 'Jacksonville International Airport', 'Jacksonville', 'United States'),
('JFK', 'John F. Kennedy International Airport', 'New York City', 'United States'),
('JLN', 'Joplin Regional Airport', 'Joplin', 'United States'),
('JMS', 'Jamestown Regional Airport', 'Jamestown', 'United States'),
('JNU', 'Juneau International Airport', 'Juneau', 'United States'),
('JST', 'Johnstown–Cambria County Airport', 'Johnstown', 'United States'),
('LAN', 'Capital Region International Airport', 'Lansing', 'United States'),
('LAR', 'Laramie Regional Airport', 'Laramie', 'United States'),
('LAS', 'Harry Reid International Airport', 'Las Vegas', 'United States'),
('LAW', 'Lawton–Fort Sill Regional Airport', 'Lawton', 'United States'),
('LAX', 'Los Angeles International Airport', 'Los Angeles', 'United States'),
('LBB', 'Lubbock Preston Smith International Airport', 'Lubbock', 'United States'),
('LBE', 'Arnold Palmer Regional Airport', 'Latrobe', 'United States'),
('LBL', 'Liberal Mid-America Regional Airport', 'Liberal', 'United States'),
('LCH', 'Lake Charles Regional Airport', 'Lake Charles', 'United States'),
('LEX', 'Blue Grass Airport', 'Lexington', 'United States'),
('LFT', 'Lafayette Regional Airport', 'Lafayette', 'United States'),
('LGA', 'LaGuardia Airport', 'New York City', 'United States'),
('LGB', 'Long Beach Airport', 'Long Beach', 'United States'),
('LIT', 'Bill and Hillary Clinton National Airport', 'Little Rock', 'United States'),
('LMT', 'Klamath Falls Airport', 'Klamath Falls', 'United States'),
('LNK', 'Lincoln Airport', 'Lincoln', 'United States'),
('LRD', 'Laredo International Airport', 'Laredo', 'United States'),
('LSE', 'La Crosse Regional Airport', 'La Crosse', 'United States'),
('LWS', 'Lewiston–Nez Perce County Airport', 'Lewiston', 'United States'),
('LYH', 'Lynchburg Regional Airport', 'Lynchburg', 'United States'),
('MAF', 'Midland International Air and Space Port', 'Midland', 'United States'),
('MBS', 'MBS International Airport', 'Freeland', 'United States'),
('MCI', 'Kansas City International Airport', 'Kansas City', 'United States'),
('MCK', 'McCook Ben Nelson Regional Airport', 'McCook', 'United States'),
('MCO', 'Orlando International Airport', 'Orlando', 'United States'),
('MDT', 'Harrisburg International Airport', 'Harrisburg', 'United States'),
('MDW', 'Midway International Airport', 'Chicago', 'United States'),
('MEI', 'Meridian Regional Airport', 'Meridian', 'United States'),
('MEM', 'Memphis International Airport', 'Memphis', 'United States'),
('MFE', 'McAllen Miller International Airport', 'McAllen', 'United States'),
('MFR', 'Rogue Valley International–Medford Airport', 'Medford', 'United States'),
('MGM', 'Montgomery Regional Airport', 'Montgomery', 'United States'),
('MHK', 'Manhattan Regional Airport', 'Manhattan', 'United States'),
('MHT', 'Manchester–Boston Regional Airport', 'Manchester', 'United States'),
('MIA', 'Miami International Airport', 'Miami', 'United States'),
('MKE', 'Milwaukee Mitchell International Airport', 'Milwaukee', 'United States'),
('MKG', 'Muskegon County Airport', 'Muskegon', 'United States'),
('MLB', 'Melbourne Orlando International Airport', 'Melbourne', 'United States'),
('MLI', 'Quad City International Airport', 'Moline', 'United States'),
('MLU', 'Monroe Regional Airport', 'Monroe', 'United States'),
('MMH', 'Mammoth Yosemite Airport', 'Mammoth Lakes', 'United States'),
('MOB', 'Mobile Regional Airport', 'Mobile', 'United States'),
('MOD', 'Modesto City–County Airport', 'Modesto', 'United States'),
('MOT', 'Minot International Airport', 'Minot', 'United States'),
('MQT', 'Marquette Sawyer Regional Airport', 'Marquette', 'United States'),
('MRY', 'Monterey Regional Airport', 'Monterey', 'United States'),
('MSN', 'Dane County Regional Airport', 'Madison', 'United States'),
('MSO', 'Missoula International Airport', 'Missoula', 'United States'),
('MSP', 'Minneapolis–Saint Paul International Airport', 'Minneapolis', 'United States'),
('MSY', 'Louis Armstrong New Orleans International Airport', 'New Orleans', 'United States'),
('MTJ', 'Montrose Regional Airport', 'Montrose', 'United States'),
('MVY', 'Martha''s Vineyard Airport', 'Vineyard Haven', 'United States'),
('MYR', 'Myrtle Beach International Airport', 'Myrtle Beach', 'United States')
ON CONFLICT (iata_code) DO UPDATE SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  country = EXCLUDED.country;