-- Insert additional airport codes (batch 4) with city name refinements
INSERT INTO public.airport_codes (iata_code, name, city, country) VALUES
('OAJ', 'Albert J. Ellis Airport', 'Jacksonville', 'United States'),
('OAK', 'Oakland International Airport', 'Oakland', 'United States'),
('OGD', 'Ogden-Hinckley Airport', 'Ogden', 'United States'),
('OGG', 'Kahului Airport', 'Maui', 'United States'),
('OGS', 'Ogdensburg International Airport', 'Ogdensburg', 'United States'),
('OKC', 'Will Rogers World Airport', 'Oklahoma City', 'United States'),
('OLM', 'Olympia Regional Airport', 'Olympia', 'United States'),
('OMA', 'Eppley Airfield', 'Omaha', 'United States'),
('OME', 'Nome Airport', 'Nome', 'United States'),
('ONT', 'Ontario International Airport', 'Ontario', 'United States'),
('ORD', 'O''Hare International Airport', 'Chicago', 'United States'),
('ORF', 'Norfolk International Airport', 'Norfolk', 'United States'),
('ORH', 'Worcester Regional Airport', 'Worcester', 'United States'),
('OTH', 'Southwest Oregon Regional Airport', 'North Bend', 'United States'),
('OTZ', 'Ralph Wien Memorial Airport', 'Kotzebue', 'United States'),
('PAE', 'Paine Field Everett', 'Everett', 'United States'),
('PBG', 'Plattsburgh International Airport', 'Plattsburgh', 'United States'),
('PBI', 'Palm Beach International Airport', 'West Palm Beach', 'United States'),
('PDX', 'Portland International Airport', 'Portland', 'United States'),
('PHF', 'Newport News/Williamsburg International Airport', 'Newport News', 'United States'),
('PHL', 'Philadelphia International Airport', 'Philadelphia', 'United States'),
('PHX', 'Phoenix Sky Harbor International Airport', 'Phoenix', 'United States'),
('PIA', 'General Wayne A. Downing Peoria International Airport', 'Peoria', 'United States'),
('PIB', 'Hattiesburg–Laurel Regional Airport', 'Hattiesburg/Laurel', 'United States'),
('PIH', 'Pocatello Regional Airport', 'Pocatello', 'United States'),
('PIT', 'Pittsburgh International Airport', 'Pittsburgh', 'United States'),
('PLN', 'Pellston Regional Airport', 'Pellston', 'United States'),
('PNS', 'Pensacola International Airport', 'Pensacola', 'United States'),
('PPG', 'Pago Pago International Airport', 'Pago Pago', 'American Samoa'),
('PSC', 'Tri-Cities Airport', 'Pasco', 'United States'),
('PSE', 'Mercedita Airport', 'Ponce', 'Puerto Rico'),
('PSG', 'Petersburg James A. Johnson Airport', 'Petersburg', 'United States'),
('PSP', 'Palm Springs International Airport', 'Palm Springs', 'United States'),
('PUB', 'Pueblo Memorial Airport', 'Pueblo', 'United States'),
('PVD', 'T. F. Green Airport', 'Providence', 'United States'),
('PWM', 'Portland International Jetport', 'Portland', 'United States'),
('RAP', 'Rapid City Regional Airport', 'Rapid City', 'United States'),
('RDU', 'Raleigh–Durham International Airport', 'Raleigh/Durham', 'United States'),
('RHI', 'Rhinelander–Oneida County Airport', 'Rhinelander', 'United States'),
('RIC', 'Richmond International Airport', 'Richmond', 'United States'),
('RKS', 'Southwest Wyoming Regional Airport', 'Rock Springs', 'United States'),
('RNO', 'Reno–Tahoe International Airport', 'Reno', 'United States'),
('ROA', 'Roanoke–Blacksburg Regional Airport', 'Roanoke', 'United States'),
('ROC', 'Greater Rochester International Airport', 'Rochester', 'United States'),
('ROW', 'Roswell International Air Center', 'Roswell', 'United States'),
('RST', 'Rochester International Airport', 'Rochester', 'United States'),
('RSW', 'Southwest Florida International Airport', 'Fort Myers', 'United States'),
('SAF', 'Santa Fe Regional Airport', 'Santa Fe', 'United States'),
('SAN', 'San Diego International Airport', 'San Diego', 'United States'),
('SAT', 'San Antonio International Airport', 'San Antonio', 'United States'),
('SAV', 'Savannah/Hilton Head International Airport', 'Savannah', 'United States'),
('SBA', 'Santa Barbara Municipal Airport', 'Santa Barbara', 'United States'),
('SBN', 'South Bend International Airport', 'South Bend', 'United States'),
('SBP', 'San Luis Obispo County Regional Airport', 'San Luis Obispo', 'United States'),
('SCC', 'Deadhorse Airport', 'Deadhorse', 'United States'),
('SCE', 'University Park Airport', 'State College', 'United States'),
('SDF', 'Louisville Muhammad Ali International Airport', 'Louisville', 'United States'),
('SEA', 'Seattle–Tacoma International Airport', 'Seattle', 'United States'),
('SFO', 'San Francisco International Airport', 'San Francisco', 'United States'),
('SGF', 'Springfield–Branson National Airport', 'Springfield', 'United States'),
('SGU', 'St. George Regional Airport', 'St. George', 'United States'),
('SHV', 'Shreveport Regional Airport', 'Shreveport', 'United States'),
('SIT', 'Sitka Rocky Gutierrez Airport', 'Sitka', 'United States'),
('SJC', 'San Jose International Airport', 'San Jose', 'United States'),
('SJT', 'San Angelo Regional Airport', 'San Angelo', 'United States'),
('SJU', 'Luis Muñoz Marín International Airport', 'San Juan', 'Puerto Rico'),
('SLC', 'Salt Lake City International Airport', 'Salt Lake City', 'United States'),
('SMF', 'Sacramento International Airport', 'Sacramento', 'United States'),
('SMX', 'Santa Maria Public Airport', 'Santa Maria', 'United States'),
('SNA', 'John Wayne Airport', 'Orange County', 'United States'),
('SPI', 'Abraham Lincoln Capital Airport', 'Springfield', 'United States'),
('SPS', 'Sheppard Air Force Base/Wichita Falls Municipal Airport', 'Wichita Falls', 'United States'),
('SRQ', 'Sarasota–Bradenton International Airport', 'Sarasota', 'United States'),
('STC', 'St. Cloud Regional Airport', 'St. Cloud', 'United States'),
('STL', 'St. Louis Lambert International Airport', 'St. Louis', 'United States'),
('STT', 'Cyril E. King Airport', 'Charlotte Amalie', 'United States Virgin Islands'),
('STX', 'Henry E. Rohlsen Airport', 'Christiansted', 'United States Virgin Islands'),
('SUN', 'Friedman Memorial Airport', 'Hailey', 'United States'),
('SUX', 'Sioux Gateway Airport', 'Sioux City', 'United States'),
('SWF', 'Stewart International Airport', 'New Windsor', 'United States'),
('SYR', 'Syracuse Hancock International Airport', 'Syracuse', 'United States'),
('TLH', 'Tallahassee International Airport', 'Tallahassee', 'United States'),
('TOL', 'Toledo Express Airport', 'Toledo', 'United States'),
('TPA', 'Tampa International Airport', 'Tampa', 'United States'),
('TRI', 'Tri-Cities Regional Airport', 'Blountville', 'United States'),
('TTN', 'Trenton–Mercer Airport', 'Trenton', 'United States'),
('TUL', 'Tulsa International Airport', 'Tulsa', 'United States'),
('TUS', 'Tucson International Airport', 'Tucson', 'United States'),
('TVC', 'Cherry Capital Airport', 'Traverse City', 'United States'),
('TWF', 'Magic Valley Regional Airport', 'Twin Falls', 'United States'),
('TXK', 'Texarkana Regional Airport', 'Texarkana', 'United States'),
('TYR', 'Tyler Pounds Regional Airport', 'Tyler', 'United States'),
('TYS', 'McGhee Tyson Airport', 'Knoxville', 'United States'),
('UST', 'Northeast Florida Regional Airport', 'St. Augustine', 'United States'),
('VLD', 'Valdosta Regional Airport', 'Valdosta', 'United States'),
('VPS', 'Destin–Fort Walton Beach Airport', 'Valparaiso', 'United States'),
('WRG', 'Wrangell Airport', 'Wrangell', 'United States'),
('WYS', 'Yellowstone Airport', 'West Yellowstone', 'United States'),
('XNA', 'Northwest Arkansas National Airport', 'Fayetteville', 'United States'),
('YAK', 'Yakutat Airport', 'Yakutat', 'United States'),
('YUM', 'Yuma International Airport', 'Yuma', 'United States')
ON CONFLICT (iata_code) DO UPDATE SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  country = EXCLUDED.country;