-- Fix existing security events data and constraint

-- First, let's update any invalid event types to a generic one
UPDATE public.security_events 
SET event_type = 'security_event_logged'
WHERE event_type NOT IN (
    'login_success',
    'login_failure', 
    'forced_logout',
    'session_validation_failed',
    'unauthorized_access_attempt',
    'session_expired',
    'device_fingerprint_mismatch',
    'session_hijacking_detected',
    'security_config_updated',
    'mfa_setup_initiated',
    'manual_security_verification',
    'suspicious_email_attempt',
    'suspicious_email_input',
    'form_validation_failure',
    'sql_injection_attempt',
    'xss_attempt',
    'potential_xss_attempt',
    'malicious_input_blocked',
    'suspicious_input_detected',
    'rate_limit_exceeded',
    'repeated_unauthorized_attempts',
    'suspicious_activity_pattern',
    'forced_security_logout',
    'forced_logout_anomaly',
    'sensitive_data_accessed',
    'data_encrypted',
    'data_decrypted',
    'encryption_failed', 
    'decryption_failed',
    'data_validation_failed',
    'unauthorized_sensitive_access',
    'sensitive_data_access',
    'client_data_accessed',
    'cross_user_client_access',
    'admin_client_data_access',
    'manager_team_client_access',
    'supervisor_team_client_access',
    'unauthorized_client_access_attempt',
    'sensitive_client_data_modified',
    'admin_override_access',
    'missing_security_headers',
    'security_headers_validated',
    'threat_hunt_initiated',
    'compliance_report_generated',
    'compliance_report_downloaded',
    'audit_data_accessed',
    'critical_security_incident',
    'lockdown_initiated',
    'monitoring_error',
    'validation_error',
    'access_control_error',
    'unknown_table_access',
    'gmail_credentials_updated',
    'option_review_token_generated',
    'option_token_accessed',
    'option_token_access_denied', 
    'invalid_option_token_attempt',
    'invalid_oauth_state_token',
    'token_storage_blocked',
    'client_data_select',
    'client_data_insert', 
    'client_data_update',
    'client_data_delete',
    'sensitive_table_access',
    'unauthenticated_access_attempt',
    'security_event_logged',
    'security_scan_completed',
    'anomaly_detected'
);

-- Now add the constraint
ALTER TABLE public.security_events 
ADD CONSTRAINT security_events_event_type_check 
CHECK (event_type IN (
    'login_success', 'login_failure', 'forced_logout', 'session_validation_failed',
    'unauthorized_access_attempt', 'session_expired', 'device_fingerprint_mismatch',
    'session_hijacking_detected', 'security_config_updated', 'mfa_setup_initiated',
    'manual_security_verification', 'suspicious_email_attempt', 'suspicious_email_input',
    'form_validation_failure', 'sql_injection_attempt', 'xss_attempt', 'potential_xss_attempt',
    'malicious_input_blocked', 'suspicious_input_detected', 'rate_limit_exceeded',
    'repeated_unauthorized_attempts', 'suspicious_activity_pattern', 'forced_security_logout',
    'forced_logout_anomaly', 'sensitive_data_accessed', 'data_encrypted', 'data_decrypted',
    'encryption_failed', 'decryption_failed', 'data_validation_failed', 'unauthorized_sensitive_access',
    'sensitive_data_access', 'client_data_accessed', 'cross_user_client_access', 'admin_client_data_access',
    'manager_team_client_access', 'supervisor_team_client_access', 'unauthorized_client_access_attempt',
    'sensitive_client_data_modified', 'admin_override_access', 'missing_security_headers',
    'security_headers_validated', 'threat_hunt_initiated', 'compliance_report_generated',
    'compliance_report_downloaded', 'audit_data_accessed', 'critical_security_incident',
    'lockdown_initiated', 'monitoring_error', 'validation_error', 'access_control_error',
    'unknown_table_access', 'gmail_credentials_updated', 'option_review_token_generated',
    'option_token_accessed', 'option_token_access_denied', 'invalid_option_token_attempt',
    'invalid_oauth_state_token', 'token_storage_blocked', 'client_data_select', 'client_data_insert',
    'client_data_update', 'client_data_delete', 'sensitive_table_access', 'unauthenticated_access_attempt',
    'security_event_logged', 'security_scan_completed', 'anomaly_detected'
));