-- Insert additional airport codes (batch 6) with new entries and refined data
INSERT INTO public.airport_codes (iata_code, name, city, country) VALUES
('CAE', 'Columbia Metropolitan Airport', 'Columbia', 'United States'),
('CAK', 'Akron–Canton Airport', 'Akron', 'United States'),
('CDC', 'Cedar City Regional Airport', 'Cedar City', 'United States'),
('CDV', 'Merle K. (Mudhole) Smith Airport', 'Cordova', 'United States'),
('CEC', 'Del Norte County Regional Airport', 'Crescent City', 'United States'),
('CEM', 'Central Airport', 'Central', 'United States'),
('CEZ', 'Cortez Municipal Airport', 'Cortez', 'United States'),
('CHA', 'Chattanooga Metropolitan Airport', 'Chattanooga', 'United States'),
('CHO', 'Charlottesville–Albemarle Airport', 'Charlottesville', 'United States'),
('CHS', 'Charleston International Airport', 'Charleston', 'United States'),
('CIC', 'Chico Municipal Airport', 'Chico', 'United States'),
('CID', 'Eastern Iowa Airport', 'Cedar Rapids', 'United States'),
('CIU', 'Chippewa County International Airport', 'Sault Ste. Marie', 'United States'),
('CKB', 'North Central West Virginia Airport', 'Clarksburg', 'United States'),
('CLE', 'Cleveland Hopkins International Airport', 'Cleveland', 'United States'),
('CLL', 'Easterwood Airport', 'College Station', 'United States'),
('CLM', 'William R. Fairchild International Airport', 'Port Angeles', 'United States'),
('CLT', 'Charlotte Douglas International Airport', 'Charlotte', 'United States'),
('CMH', 'John Glenn Columbus International Airport', 'Columbus', 'United States'),
('CMI', 'University of Illinois Willard Airport', 'Champaign', 'United States'),
('CMX', 'Houghton County Memorial Airport', 'Hancock', 'United States'),
('CNY', 'Canyonlands Field', 'Moab', 'United States'),
('COD', 'Yellowstone Regional Airport', 'Cody', 'United States'),
('COS', 'Colorado Springs Airport', 'Colorado Springs', 'United States'),
('COU', 'Columbia Regional Airport', 'Columbia', 'United States'),
('CPR', 'Casper–Natrona County International Airport', 'Casper', 'United States'),
('CRP', 'Corpus Christi International Airport', 'Corpus Christi', 'United States'),
('CRW', 'Yeager Airport', 'Charleston', 'United States'),
('CSG', 'Columbus Metropolitan Airport', 'Columbus', 'United States'),
('CVG', 'Cincinnati/Northern Kentucky International Airport', 'Covington', 'United States'),
('CWA', 'Central Wisconsin Airport', 'Mosinee', 'United States'),
('DAB', 'Daytona Beach International Airport', 'Daytona Beach', 'United States'),
('DAL', 'Dallas Love Field', 'Dallas', 'United States'),
('DAY', 'Dayton International Airport', 'Dayton', 'United States'),
('DBQ', 'Dubuque Regional Airport', 'Dubuque', 'United States'),
('DCA', 'Ronald Reagan Washington National Airport', 'Arlington', 'United States'),
('DEN', 'Denver International Airport', 'Denver', 'United States'),
('DFW', 'Dallas/Fort Worth International Airport', 'Dallas/Fort Worth', 'United States'),
('DHN', 'Dothan Regional Airport', 'Dothan', 'United States'),
('DLG', 'Dillingham Airport', 'Dillingham', 'United States'),
('DLH', 'Duluth International Airport', 'Duluth', 'United States'),
('DRO', 'Durango–La Plata County Airport', 'Durango', 'United States'),
('DRT', 'Del Rio International Airport', 'Del Rio', 'United States'),
('DSM', 'Des Moines International Airport', 'Des Moines', 'United States'),
('DTW', 'Detroit Metropolitan Wayne County Airport', 'Detroit', 'United States'),
('DVL', 'Devils Lake Regional Airport', 'Devils Lake', 'United States'),
('EAR', 'Kearney Regional Airport', 'Kearney', 'United States'),
('EAT', 'Pangborn Memorial Airport', 'Wenatchee', 'United States'),
('EAU', 'Chippewa Valley Regional Airport', 'Eau Claire', 'United States'),
('ECP', 'Northwest Florida Beaches International Airport', 'Panama City', 'United States'),
('EGE', 'Eagle County Regional Airport', 'Eagle', 'United States'),
('EKO', 'Elko Regional Airport', 'Elko', 'United States'),
('ELM', 'Elmira/Corning Regional Airport', 'Elmira', 'United States'),
('ELP', 'El Paso International Airport', 'El Paso', 'United States'),
('ERI', 'Erie International Airport', 'Erie', 'United States'),
('ESC', 'Delta County Airport', 'Escanaba', 'United States'),
('EUG', 'Eugene Airport', 'Eugene', 'United States'),
('EVV', 'Evansville Regional Airport', 'Evansville', 'United States'),
('EWN', 'Coastal Carolina Regional Airport', 'New Bern', 'United States'),
('EWR', 'Newark Liberty International Airport', 'Newark', 'United States'),
('EYW', 'Key West International Airport', 'Key West', 'United States'),
('FAR', 'Hector International Airport', 'Fargo', 'United States'),
('FAT', 'Fresno Yosemite International Airport', 'Fresno', 'United States'),
('FAY', 'Fayetteville Regional Airport', 'Fayetteville', 'United States'),
('FLG', 'Flagstaff Pulliam Airport', 'Flagstaff', 'United States'),
('FLL', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale', 'United States'),
('FLO', 'Florence Regional Airport', 'Florence', 'United States'),
('FNT', 'Flint Bishop International Airport', 'Flint', 'United States'),
('FOD', 'Fort Dodge Regional Airport', 'Fort Dodge', 'United States'),
('FSD', 'Sioux Falls Regional Airport', 'Sioux Falls', 'United States'),
('FSM', 'Fort Smith Regional Airport', 'Fort Smith', 'United States'),
('FWA', 'Fort Wayne International Airport', 'Fort Wayne', 'United States'),
('GCC', 'Gillette–Campbell County Airport', 'Gillette', 'United States'),
('GCK', 'Garden City Regional Airport', 'Garden City', 'United States'),
('GEG', 'Spokane International Airport', 'Spokane', 'United States'),
('GFK', 'Grand Forks International Airport', 'Grand Forks', 'United States'),
('GGG', 'East Texas Regional Airport', 'Longview', 'United States'),
('GJT', 'Grand Junction Regional Airport', 'Grand Junction', 'United States'),
('GLH', 'Mid Delta Regional Airport', 'Greenville', 'United States'),
('GNV', 'Gainesville Regional Airport', 'Gainesville', 'United States'),
('GPT', 'Gulfport–Biloxi International Airport', 'Gulfport', 'United States'),
('GRB', 'Green Bay–Austin Straubel International Airport', 'Green Bay', 'United States'),
('GRI', 'Central Nebraska Regional Airport', 'Grand Island', 'United States'),
('GRK', 'Killeen–Fort Hood Regional Airport', 'Killeen', 'United States'),
('GRR', 'Gerald R. Ford International Airport', 'Grand Rapids', 'United States'),
('GSO', 'Piedmont Triad International Airport', 'Greensboro', 'United States'),
('GSP', 'Greenville–Spartanburg International Airport', 'Greer', 'United States'),
('GST', 'Gustavus Airport', 'Gustavus', 'United States'),
('GTF', 'Great Falls International Airport', 'Great Falls', 'United States'),
('GTR', 'Golden Triangle Regional Airport', 'Columbus', 'United States'),
('GUC', 'Gunnison–Crested Butte Regional Airport', 'Gunnison', 'United States'),
('GUM', 'Antonio B. Won Pat International Airport', 'Hagåtña', 'Guam'),
('HDN', 'Yampa Valley Airport', 'Hayden', 'United States'),
('HIB', 'Range Regional Airport', 'Hibbing', 'United States'),
('HLN', 'Helena Regional Airport', 'Helena', 'United States'),
('HNL', 'Daniel K. Inouye International Airport', 'Honolulu', 'United States'),
('HOB', 'Lea County Regional Airport', 'Hobbs', 'United States'),
('HOU', 'William P. Hobby Airport', 'Houston', 'United States'),
('HPN', 'Westchester County Airport', 'White Plains', 'United States'),
('HRL', 'Valley International Airport', 'Harlingen', 'United States'),
('HSV', 'Huntsville International Airport', 'Huntsville', 'United States'),
('HTS', 'Tri-State Airport', 'Huntington', 'United States'),
('HYA', 'Barnstable Municipal Airport', 'Hyannis', 'United States'),
('HYS', 'Hays Regional Airport', 'Hays', 'United States'),
('IAD', 'Washington Dulles International Airport', 'Dulles', 'United States'),
('IAG', 'Niagara Falls International Airport', 'Niagara Falls', 'United States'),
('IAH', 'George Bush Intercontinental Airport', 'Houston', 'United States'),
('ICT', 'Wichita Dwight D. Eisenhower National Airport', 'Wichita', 'United States'),
('IDA', 'Idaho Falls Regional Airport', 'Idaho Falls', 'United States')
ON CONFLICT (iata_code) DO UPDATE SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  country = EXCLUDED.country;