-- Insert additional international airport codes (batch 8)
INSERT INTO public.airport_codes (iata_code, name, city, country) VALUES
('ADB', 'Adnan Menderes Airport', 'Izmir', 'Turkey'),
('ALA', 'Almaty International Airport', 'Almaty', 'Kazakhstan'),
('ALG', 'Houari Boumediene Airport', 'Algiers', 'Algeria'),
('AMM', 'Queen Alia International Airport', 'Amman', 'Jordan'),
('ARN', 'Stockholm Arlanda Airport', 'Stockholm', 'Sweden'),
('ASB', 'Ashgabat International Airport', 'Ashgabat', 'Turkmenistan'),
('BAH', 'Bahrain International Airport', 'Manama', 'Bahrain'),
('BEG', 'Belgrade Nikola Tesla Airport', 'Belgrade', 'Serbia'),
('BGY', 'Orio al Serio International Airport', 'Bergamo', 'Italy'),
('BLL', 'Billund Airport', 'Billund', 'Denmark'),
('BLR', 'Kempegowda International Airport', 'Bangalore', 'India'),
('BNE', 'Brisbane Airport', 'Brisbane', 'Australia'),
('BSL', 'EuroAirport Basel–Mulhouse–Freiburg', 'Basel', 'Switzerland'),
('BTS', 'Bratislava Airport', 'Bratislava', 'Slovakia'),
('CHC', 'Christchurch International Airport', 'Christchurch', 'New Zealand'),
('CKG', 'Chongqing Jiangbei International Airport', 'Chongqing', 'China'),
('CMN', 'Mohammed V International Airport', 'Casablanca', 'Morocco'),
('CPH', 'Copenhagen Airport', 'Copenhagen', 'Denmark'),
('CTU', 'Chengdu Shuangliu International Airport', 'Chengdu', 'China'),
('CUZ', 'Velasco Astete International Airport', 'Cusco', 'Peru'),
('DAR', 'Julius Nyerere International Airport', 'Dar es Salaam', 'Tanzania'),
('DPS', 'Ngurah Rai International Airport (Bali)', 'Denpasar', 'Indonesia'),
('DRS', 'Dresden Airport', 'Dresden', 'Germany'),
('DUS', 'Düsseldorf Airport', 'Düsseldorf', 'Germany'),
('ELD', 'El Dorado Airport', 'El Dorado', 'United States'),
('EVN', 'Zvartnots International Airport', 'Yerevan', 'Armenia'),
('EVV', 'Evansville Regional Airport', 'Evansville', 'United States'),
('FEZ', 'Fès–Saïs Airport', 'Fez', 'Morocco'),
('FIH', 'N''djili Airport', 'Kinshasa', 'Democratic Republic of the Congo'),
('FNC', 'Cristiano Ronaldo Madeira International Airport', 'Funchal', 'Portugal'),
('FOR', 'Pinto Martins – Fortaleza International Airport', 'Fortaleza', 'Brazil'),
('GEG', 'Spokane International Airport', 'Spokane', 'United States'),
('GOA', 'Genoa Cristoforo Colombo Airport', 'Genoa', 'Italy'),
('GOT', 'Gothenburg Landvetter Airport', 'Gothenburg', 'Sweden'),
('GUM', 'Antonio B. Won Pat International Airport', 'Guam', 'Guam'),
('HAN', 'Noi Bai International Airport', 'Hanoi', 'Vietnam'),
('HEL', 'Helsinki–Vantaa Airport', 'Helsinki', 'Finland'),
('HKT', 'Phuket International Airport', 'Phuket', 'Thailand'),
('HRB', 'Harbin Taiping International Airport', 'Harbin', 'China'),
('HYD', 'Rajiv Gandhi International Airport', 'Hyderabad', 'India'),
('IKA', 'Imam Khomeini International Airport', 'Tehran', 'Iran'),
('ISB', 'Islamabad International Airport', 'Islamabad', 'Pakistan'),
('JED', 'King Abdulaziz International Airport', 'Jeddah', 'Saudi Arabia'),
('JNB', 'O. R. Tambo International Airport', 'Johannesburg', 'South Africa'),
('KBP', 'Boryspil International Airport', 'Kyiv', 'Ukraine'),
('KHI', 'Jinnah International Airport', 'Karachi', 'Pakistan'),
('KMG', 'Kunming Changshui International Airport', 'Kunming', 'China'),
('KRK', 'John Paul II International Airport Kraków–Balice', 'Kraków', 'Poland'),
('KTM', 'Tribhuvan International Airport', 'Kathmandu', 'Nepal'),
('KWI', 'Kuwait International Airport', 'Kuwait City', 'Kuwait'),
('LAD', 'Quatro de Fevereiro Airport', 'Luanda', 'Angola'),
('LED', 'Pulkovo Airport', 'Saint Petersburg', 'Russia'),
('LHE', 'Allama Iqbal International Airport', 'Lahore', 'Pakistan'),
('LJU', 'Jože Pučnik Airport', 'Ljubljana', 'Slovenia'),
('LOS', 'Murtala Muhammed International Airport', 'Lagos', 'Nigeria'),
('LTN', 'London Luton Airport', 'London', 'United Kingdom'),
('LUX', 'Luxembourg Airport', 'Luxembourg', 'Luxembourg'),
('MAA', 'Chennai International Airport', 'Chennai', 'India'),
('MAN', 'Manchester Airport', 'Manchester', 'United Kingdom'),
('MBA', 'Moi International Airport', 'Mombasa', 'Kenya'),
('MLE', 'Velana International Airport', 'Malé', 'Maldives'),
('MPM', 'Maputo International Airport', 'Maputo', 'Mozambique'),
('MRU', 'SSR International Airport', 'Port Louis', 'Mauritius'),
('MVD', 'Carrasco International Airport', 'Montevideo', 'Uruguay'),
('MXP', 'Milan Malpensa Airport', 'Milan', 'Italy'),
('NBO', 'Jomo Kenyatta International Airport', 'Nairobi', 'Kenya'),
('NCE', 'Nice Côte d''Azur Airport', 'Nice', 'France'),
('NGO', 'Chubu Centrair International Airport', 'Nagoya', 'Japan'),
('NSI', 'Yaoundé Nsimalen International Airport', 'Yaoundé', 'Cameroon'),
('OPO', 'Francisco Sá Carneiro Airport', 'Porto', 'Portugal'),
('ORY', 'Orly Airport', 'Paris', 'France'),
('OSR', 'Leoš Janáček Airport Ostrava', 'Ostrava', 'Czech Republic'),
('OTP', 'Henri Coandă International Airport', 'Bucharest', 'Romania'),
('PBH', 'Paro Airport', 'Paro', 'Bhutan'),
('PEN', 'Penang International Airport', 'Penang', 'Malaysia'),
('PER', 'Perth Airport', 'Perth', 'Australia'),
('PHC', 'Port Harcourt International Airport', 'Port Harcourt', 'Nigeria'),
('PNH', 'Phnom Penh International Airport', 'Phnom Penh', 'Cambodia'),
('POZ', 'Poznań–Ławica Airport', 'Poznań', 'Poland'),
('PUS', 'Gimhae International Airport', 'Busan', 'South Korea'),
('RAK', 'Marrakesh Menara Airport', 'Marrakesh', 'Morocco'),
('RIX', 'Riga International Airport', 'Riga', 'Latvia'),
('RNB', 'Ronneby Airport', 'Ronneby', 'Sweden'),
('RNS', 'Rennes–Saint-Jacques Airport', 'Rennes', 'France'),
('ROS', 'Islas Malvinas Airport', 'Rosario', 'Argentina'),
('SAW', 'Sabiha Gökçen International Airport', 'Istanbul', 'Turkey'),
('SCQ', 'Santiago de Compostela Airport', 'Santiago de Compostela', 'Spain'),
('SDQ', 'Las Américas International Airport', 'Santo Domingo', 'Dominican Republic'),
('SEZ', 'Seychelles International Airport', 'Victoria', 'Seychelles'),
('SGN', 'Tan Son Nhat International Airport', 'Ho Chi Minh City', 'Vietnam'),
('SHA', 'Shanghai Hongqiao International Airport', 'Shanghai', 'China'),
('SHE', 'Shenyang Taoxian International Airport', 'Shenyang', 'China'),
('SHJ', 'Sharjah International Airport', 'Sharjah', 'United Arab Emirates'),
('SKG', 'Thessaloniki Airport', 'Thessaloniki', 'Greece'),
('SLC', 'Salt Lake City International Airport', 'Salt Lake City', 'United States'),
('SOU', 'Southampton Airport', 'Southampton', 'United Kingdom'),
('SPU', 'Split Airport', 'Split', 'Croatia'),
('SSH', 'Sharm El Sheikh International Airport', 'Sharm El Sheikh', 'Egypt'),
('STN', 'London Stansted Airport', 'London', 'United Kingdom'),
('STR', 'Stuttgart Airport', 'Stuttgart', 'Germany'),
('SZG', 'Salzburg Airport', 'Salzburg', 'Austria'),
('SZV', 'Suzhou Guangfu Airport', 'Suzhou', 'China'),
('TBS', 'Tbilisi International Airport', 'Tbilisi', 'Georgia'),
('TGU', 'Toncontín International Airport', 'Tegucigalpa', 'Honduras'),
('TIV', 'Tivat Airport', 'Tivat', 'Montenegro'),
('TLV', 'Ben Gurion Airport', 'Tel Aviv', 'Israel'),
('TNG', 'Tangier Ibn Battouta Airport', 'Tangier', 'Morocco'),
('TRN', 'Turin Airport', 'Turin', 'Italy'),
('TUN', 'Tunis–Carthage International Airport', 'Tunis', 'Tunisia'),
('TXL', 'Berlin Tegel Airport', 'Berlin', 'Germany'),
('UBN', 'Ulaanbaatar New Airport', 'Ulaanbaatar', 'Mongolia'),
('UIO', 'Mariscal Sucre International Airport', 'Quito', 'Ecuador'),
('ULN', 'Chinggis Khaan International Airport', 'Ulaanbaatar', 'Mongolia'),
('URC', 'Urumqi Diwopu International Airport', 'Urumqi', 'China'),
('VDA', 'Ovda Airport', 'Eilat', 'Israel'),
('VIE', 'Vienna International Airport', 'Vienna', 'Austria'),
('VKO', 'Vnukovo International Airport', 'Moscow', 'Russia'),
('VNO', 'Vilnius Airport', 'Vilnius', 'Lithuania'),
('VRA', 'Juan Gualberto Gómez Airport', 'Varadero', 'Cuba'),
('YOW', 'Ottawa Macdonald–Cartier International Airport', 'Ottawa', 'Canada'),
('YUL', 'Montréal–Trudeau International Airport', 'Montreal', 'Canada'),
('ZAG', 'Zagreb Airport', 'Zagreb', 'Croatia'),
('ZIA', 'Zhukovsky International Airport', 'Moscow', 'Russia'),
('ZQN', 'Queenstown Airport', 'Queenstown', 'New Zealand'),
('ZRH', 'Zurich Airport', 'Zurich', 'Switzerland')
ON CONFLICT (iata_code) DO UPDATE SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  country = EXCLUDED.country;