-- Insert additional airport codes (batch 5) with new and refined data
INSERT INTO public.airport_codes (iata_code, name, city, country) VALUES
('ABE', 'Lehigh Valley International Airport', 'Allentown', 'United States'),
('ABI', 'Abilene Regional Airport', 'Abilene', 'United States'),
('ABQ', 'Albuquerque International Sunport', 'Albuquerque', 'United States'),
('ABR', 'Aberdeen Regional Airport', 'Aberdeen', 'United States'),
('ABY', 'Southwest Georgia Regional Airport', 'Albany', 'United States'),
('ACK', 'Nantucket Memorial Airport', 'Nantucket', 'United States'),
('ACT', 'Waco Regional Airport', 'Waco', 'United States'),
('ACV', 'California Redwood Coast–Humboldt County Airport', 'Arcata', 'United States'),
('ACY', 'Atlantic City International Airport', 'Atlantic City', 'United States'),
('ADM', 'Ardmore Municipal Airport', 'Ardmore', 'United States'),
('ADQ', 'Kodiak Airport', 'Kodiak', 'United States'),
('ADS', 'Addison Airport', 'Dallas', 'United States'),
('AEX', 'Alexandria International Airport', 'Alexandria', 'United States'),
('AGS', 'Augusta Regional Airport', 'Augusta', 'United States'),
('AHN', 'Athens–Ben Epps Airport', 'Athens', 'United States'),
('AID', 'Anderson Municipal Airport', 'Anderson', 'United States'),
('AIZ', 'Lee C. Fine Memorial Airport', 'Lake Ozark', 'United States'),
('AKN', 'King Salmon Airport', 'King Salmon', 'United States'),
('ALB', 'Albany International Airport', 'Albany', 'United States'),
('ALI', 'Alice International Airport', 'Alice', 'United States'),
('ALO', 'Waterloo Regional Airport', 'Waterloo', 'United States'),
('ALS', 'San Luis Valley Regional Airport', 'Alamosa', 'United States'),
('ALW', 'Walla Walla Regional Airport', 'Walla Walla', 'United States'),
('AMA', 'Rick Husband Amarillo International Airport', 'Amarillo', 'United States'),
('ANC', 'Ted Stevens Anchorage International Airport', 'Anchorage', 'United States'),
('AND', 'Anderson Regional Airport', 'Anderson', 'United States'),
('ANN', 'Annette Island Airport', 'Annette Island', 'United States'),
('ANP', 'Lee Airport', 'Annapolis', 'United States'),
('ANW', 'Ainsworth Regional Airport', 'Ainsworth', 'United States'),
('APC', 'Napa County Airport', 'Napa', 'United States'),
('APF', 'Naples Municipal Airport', 'Naples', 'United States'),
('APN', 'Alpena County Regional Airport', 'Alpena', 'United States'),
('ARA', 'Acadiana Regional Airport', 'New Iberia', 'United States'),
('ARC', 'Arctic Village Airport', 'Arctic Village', 'United States'),
('ART', 'Watertown International Airport', 'Watertown', 'United States'),
('ASE', 'Aspen/Pitkin County Airport', 'Aspen', 'United States'),
('AST', 'Astoria Regional Airport', 'Astoria', 'United States'),
('ATK', 'Atqasuk Edward Burnell Sr. Memorial Airport', 'Atqasuk', 'United States'),
('ATL', 'Hartsfield–Jackson Atlanta International Airport', 'Atlanta', 'United States'),
('ATW', 'Appleton International Airport', 'Appleton', 'United States'),
('ATY', 'Watertown Regional Airport', 'Watertown', 'United States'),
('AUG', 'Augusta State Airport', 'Augusta', 'United States'),
('AUS', 'Austin–Bergstrom International Airport', 'Austin', 'United States'),
('AVL', 'Asheville Regional Airport', 'Asheville', 'United States'),
('AVP', 'Wilkes-Barre/Scranton International Airport', 'Avoca', 'United States'),
('AZA', 'Phoenix–Mesa Gateway Airport', 'Mesa', 'United States'),
('AZO', 'Kalamazoo/Battle Creek International Airport', 'Kalamazoo', 'United States'),
('BDL', 'Bradley International Airport', 'Windsor Locks', 'United States'),
('BET', 'Bethel Airport', 'Bethel', 'United States'),
('BFD', 'Bradford Regional Airport', 'Bradford', 'United States'),
('BFF', 'Western Nebraska Regional Airport', 'Scottsbluff', 'United States'),
('BFI', 'Boeing Field', 'Seattle', 'United States'),
('BFL', 'Meadows Field Airport', 'Bakersfield', 'United States'),
('BFM', 'Mobile Downtown Airport', 'Mobile', 'United States'),
('BGM', 'Greater Binghamton Airport', 'Binghamton', 'United States'),
('BGR', 'Bangor International Airport', 'Bangor', 'United States'),
('BHM', 'Birmingham–Shuttlesworth International Airport', 'Birmingham', 'United States'),
('BIL', 'Billings Logan International Airport', 'Billings', 'United States'),
('BIS', 'Bismarck Municipal Airport', 'Bismarck', 'United States'),
('BJI', 'Bemidji Regional Airport', 'Bemidji', 'United States'),
('BKG', 'Branson Airport', 'Branson', 'United States'),
('BKW', 'Raleigh County Memorial Airport', 'Beckley', 'United States'),
('BLI', 'Bellingham International Airport', 'Bellingham', 'United States'),
('BLV', 'MidAmerica St. Louis Airport', 'Belleville', 'United States'),
('BMG', 'Monroe County Airport', 'Bloomington', 'United States'),
('BMI', 'Central Illinois Regional Airport', 'Bloomington–Normal', 'United States'),
('BNA', 'Nashville International Airport', 'Nashville', 'United States'),
('BOI', 'Boise Airport', 'Boise', 'United States'),
('BOS', 'Logan International Airport', 'Boston', 'United States'),
('BPT', 'Jack Brooks Regional Airport', 'Beaumont', 'United States'),
('BQK', 'Brunswick Golden Isles Airport', 'Brunswick', 'United States'),
('BRD', 'Brainerd Lakes Regional Airport', 'Brainerd', 'United States'),
('BRO', 'Brownsville/South Padre Island International Airport', 'Brownsville', 'United States'),
('BRW', 'Barrow Wiley Post–Will Rogers Memorial Airport', 'Utqiaġvik', 'United States'),
('BTM', 'Bert Mooney Airport', 'Butte', 'United States'),
('BTR', 'Baton Rouge Metropolitan Airport', 'Baton Rouge', 'United States'),
('BTV', 'Burlington International Airport', 'Burlington', 'United States'),
('BUF', 'Buffalo Niagara International Airport', 'Buffalo', 'United States'),
('BUR', 'Bob Hope Airport', 'Burbank', 'United States'),
('BWI', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore', 'United States'),
('BZN', 'Bozeman Yellowstone International Airport', 'Bozeman', 'United States')
ON CONFLICT (iata_code) DO UPDATE SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  country = EXCLUDED.country;